# Generated by Django 3.0.5 on 2020-05-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pic',
            field=models.ImageField(default='uploads/accounts/default.jpeg', upload_to='uploads/accounts/'),
        ),
    ]
