# Generated by Django 3.0.5 on 2020-05-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200518_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlogin',
            name='email',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True, blank=True),
            preserve_default=False,
        ),
    ]
