# Generated by Django 3.0.5 on 2020-04-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
