# Generated by Django 3.0.5 on 2020-04-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_notice_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/notices/'),
        ),
    ]
