# Generated by Django 3.0.5 on 2020-04-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_notice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/notices/'),
        ),
    ]
