# Generated by Django 3.0.5 on 2020-05-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_auto_20200415_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notice',
            name='heading',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
